// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4MoBb9oBL2uT-NIr7r4ApUD8G0pJnbkc',
    appId: '1:786169926022:web:02a7d170595d4434769c07',
    messagingSenderId: '786169926022',
    projectId: 'authbolig',
    authDomain: 'authbolig.firebaseapp.com',
    storageBucket: 'authbolig.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB9_fEzt6hXgfsKpgN8tfeCmkEWIbONfg',
    appId: '1:786169926022:android:a5ad5bc9aa8ad137769c07',
    messagingSenderId: '786169926022',
    projectId: 'authbolig',
    storageBucket: 'authbolig.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpkwlggYK-6QpCd392ydkGAAo7Aar3PE',
    appId: '1:786169926022:ios:d4fe44379dfd4092769c07',
    messagingSenderId: '786169926022',
    projectId: 'authbolig',
    storageBucket: 'authbolig.appspot.com',
    iosBundleId: 'com.example.bolig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCpkwlggYK-6QpCd392ydkGAAo7Aar3PE',
    appId: '1:786169926022:ios:473a5dec46efdff9769c07',
    messagingSenderId: '786169926022',
    projectId: 'authbolig',
    storageBucket: 'authbolig.appspot.com',
    iosBundleId: 'com.example.bolig.RunnerTests',
  );
}
